# Common Labels
labels:
  app: "egov-pg-service"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "pg-service"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_pg_service_schema"
    image:
      repository: "egov-pg-service-db"

# Container Configs
image:
  repository: "egov-pg-service"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/pg-service/health"
  readinessProbePath: "/pg-service/health"
appType: "java-spring"
tracing-enabled: true
axis: true
paygov: true
payu-url: ""
payu-url-status: ""
ccavenue-status-access-code: ""
ccavenue-redirect-access-code: ""
ccavenue-url: ""
ccavenue-url-status: ""
ccavenue-url-redirect: ""
ccavenue-url-cancel: ""
heap: "-Xmx192m -Xms192m"
java-args: "-Dspring.profiles.active=monitoring"
java-debug: "true"

# Additional Container Envs
env: |
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: egov-pg-service
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_BILLINGSERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: billing-service
  - name: EGOV_USERSERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user        
  - name: EGOV_COLLECTIONSERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: collection-services
  - name: NOTIFICATION_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: EGOV_BANKACCOUNTSERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egf-master
  - name: EGOV_BUSINESSDETAILSSERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-common-masters
  {{- if .Values.axis }}
  - name: AXIS_ACTIVE
    value: "true"
  - name: AXIS_CURRENCY
    value: "INR"
  - name: AXIS_MERCHANT_VPC_VERSION    
    value: "1"
  - name: AXIS_MERCHANT_VPC_COMMAND_PAY
    value: "pay"
  - name: AXIS_MERCHANT_VPC_COMMAND_STATUS
    value: "queryDR"
  - name: AXIS_LOCALE
    value: "en_IN"
  - name: AXIS_URL_DEBIT
    value: "https://migs.mastercard.co.in/vpcpay"
  - name: AXIS_URL_STATUS
    value: "https://migs.mastercard.co.in/vpcdps"
  - name: AXIS_MERCHANT_ID
    valueFrom:
      secretKeyRef:
        name: egov-pg-service
        key: axismerchantid
  - name: AXIS_MERCHANT_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: egov-pg-service
        key: axismerchantsecret
  - name: AXIS_MERCHANT_USER
    valueFrom:
      secretKeyRef:
        name: egov-pg-service
        key: axismerchantuser
  - name: AXIS_MERCHANT_PWD
    valueFrom:
      secretKeyRef:
        name: egov-pg-service
        key: axismerchantpwd
  - name: AXIS_MERCHANT_ACCESS_CODE
    valueFrom:
      secretKeyRef:
        name: egov-pg-service
        key: axismerchantaccesscode
  {{- end }}
  {{- if index .Values "payu-url" }}
  - name: PAYU_ACTIVE
    value: "true"    
  - name: PAYU_URL
    value: {{ index .Values "payu-url" | quote }}
  - name: PAYU_URL_STATUS
    value: {{ index .Values "payu-url-status" | quote }}
  - name: PAYU_MERCHANT_KEY
    valueFrom:
      secretKeyRef:
        name: egov-pg-service
        key: payumerchantkey
  - name: PAYU_MERCHANT_SALT
    valueFrom:
      secretKeyRef:
        name: egov-pg-service
        key: payumerchantsalt 
  {{- end }}
  {{- if .Values.ccavenue }}
  - name: CCAVENUE_ACTIVE
    value: "true"
  - name: CCAVENUE_MERCHANT_ID
    valueFrom:
      secretKeyRef:
        name: egov-pg-service
        key: ccavenue-merchant-id
  - name: CCAVENUE_STATUS_WORKING_KEY
    valueFrom:
      secretKeyRef:
        name: egov-pg-service
        key: ccavenue-status-working-key
  - name: CCAVENUE_REDIRECT_WORKING_KEY
    valueFrom:
      secretKeyRef:
        name: egov-pg-service
        key: ccavenue-redirect-working-key
  - name: CCAVENUE_STATUS_ACCESS_CODE
    value: {{ index .Values "ccavenue-status-access-code" | quote }}
  - name: CCAVENUE_REDIRECT_ACCESS_CODE
    value: {{ index .Values "ccavenue-redirect-access-code" | quote }}
  - name: CCAVENUE_GATEWAY_URL
    value: {{ index .Values "ccavenue-url" | quote }}
  - name: CCAVENUE_GATEWAY_STATUS_URL
    value: {{ index .Values "ccavenue-url-status" | quote }}
  - name: CCAVENUE_REDIRECT_URL
    value: {{ index .Values "ccavenue-url-redirect" | quote }}
  - name: CCAVENUE_CANCEL_URL
    value: {{ index .Values "ccavenue-url-cancel" | quote }}
  {{- end }}
  {{- if .Values.paygov }}
  - name: PAYGOV_ACTIVE
    value: "true"
  - name: PAYGOV_MESSAGETYPE
    value: "0100"
  - name: PAYGOV_CURRENCY
    value: "INR"
  - name: PAYGOV_MERCHANT_VPC_COMMAND_PAY    
    value: "pay"
  - name: PAYGOV_MERCHANT_VPC_COMMAND_STATUS
    value: "queryDR"
  - name: PAYGOV_DATEFORMAT
    value: "dd-MM-yyyy HH:mm:SSS"
  - name: PAYGOV_GATEWAY_URL
    value: "https://pilot.surepay.ndml.in/SurePayPayment/sp/processRequest"
  - name: PAYGOV_GATEWAY_STATUS_URL
    value: "https://pilot.surepay.ndml.in/SurePayPayment/v1/queryPaymentStatus"
  - name: PAYGOV_GATEWAY_STATUS_URL_WITHIP
    value: "https://121.242.223.194/SurePayPayment/v1/queryPaymentStatus"
  - name: PAYGOV_CITIZEN_REDIRECT_DOMAIN_NAME
    value: "https://upyog.niua.org"
  - name: PAYGOV_MERCHANT_ID
    valueFrom:
      secretKeyRef:
        name: egov-pg-service
        key: paygov-merchant-id
  - name: PAYGOV_MERCHANT_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: egov-pg-service
        key: paygov-merchant-secret-key
  - name: PAYGOV_MERCHANT_USER
    valueFrom:
      secretKeyRef:
        name: egov-pg-service
        key: paygov-merchant-user
  - name: PAYGOV_MERCHANT_PWD
    valueFrom:
      secretKeyRef:
        name: egov-pg-service
        key: paygov-merchant-pwd
  {{- end }}
  {{- if .Values.nttdata }}
  - name: NTTDATA_ACTIVE
    value: "true"
  - name: NTTDATA_MERCHANT_ID
    value: "317156"
  - name: NTTDATA_REDIRECT_URL
    value: "https://upyog-test.niua.org/pg-service/transaction/v1/_redirect"
  - name: NTTDATA_GATEWAY_URL_STATUS
    value: "https://paynetzuat.atomtech.in/ots/payment/status?"
  - name: NTTDATA_GATEWAY_URL_ATOM
    value: "https://paynetzuat.atomtech.in/ots/aipay/auth?"
  - name: NTTDATA_ORIGINAL_RETURN_URL_KEY
    value: "originalreturnurl"
  - name: NTTDATA_MERCHANT_CHECKOUT_HOST
    value: "https://pgtest.atomtech.in/staticdata/ots/js/atomcheckout.js"
  {{- end }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: JAVA_ENABLE_DEBUG
    value: {{ index .Values "java-debug" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false" 
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
